### ISSUE TITLE
Any project in any language

### ISSUE THREAD

**Issue by Tamanna-S** [Kartikey0205/Program1#14]
hey @Kartikey0205 may i add my project made in python?

**Comment by Kartikey0205** [comment]
Yeah sure go ahead @Tamanna-S

**Comment by viroopaksh-utrayak** [comment]
hey!
@Kartikey0205  may i add my python project?

**Comment by Saumiya-Ranjan** [comment]
@Kartikey0205 may I add a python project .

**Comment by Kartikey0205** [comment]
Go ahead @Saumiya-Ranjan @viroopaksh-utrayak

**Comment by Kartikey0205** [comment]
@chmodx1sh go ahead

**Comment by RaghavMahexhwari** [comment]
hey @Kartikey0205 can you assign me this task?

**Comment by RaghavMahexhwari** [comment]
hi @Kartikey0205 I made a pr #30 added a new project jira ticket clone please have a look!

**Comment by Kartikey0205** [comment]
@RaghavMahexhwari  Go Ahead

**Comment by Kartikey0205** [comment]
Yeah sure Go ahead @Abhishek91520 , but make sure read the Readme first

**Comment by Jivan2801** [comment]
Can i add my project

**Comment by Satyam20i** [comment]
Can you assign this to me?

**Comment by Kartikey0205** [comment]
@Jivan2801 @Satyam20i  Go ahead
