### ISSUE TITLE
Add a program to print the pattern

### ISSUE THREAD

**Issue by Kartikey0205** [Kartikey0205/Program1#3]

**Comment by YushChaudhary** [comment]
can you assign this to me thanks

**Comment by anuragnewbie** [comment]
hi! Please assign this issue to me, I want to contribute.

**Comment by mitali-1703** [comment]
Hii , Kartikey please assign me this

**Comment by Kartikey0205** [comment]
> can you assign this to me thanks

go ahead with C++ Language @YushChaudhary
