### ISSUE TITLE
Add rock paper scissor game

### ISSUE THREAD

**Issue by Kartikey0205** [Kartikey0205/Program1#5]

**Comment by 0901IT201046** [comment]
Hey Kartikey, Please assign this issue to me.

**Comment by akarshan2602** [comment]
Hey @Kartikey0205, can i work on this? I have created tic tac toe game previously, so i am pretty confident that i will do this game too!

**Comment by san-ya** [comment]
Hi, @Kartikey0205. I have created a rock, paper, scissors game before and I'd love to contribute to this repo. Please assign it to me, thanks.

**Comment by karanS08** [comment]
Hi @Kartikey0205  , I am new guy to open sourcing but definitely not new to programming . I am 2nd year student and i would like to contribute to your repo.  I can write the program in c , c++ or python .

**Comment by Kartikey0205** [comment]
> Hi @Kartikey0205 , I am new guy to open sourcing but definitely not new to programming . I am 2nd year student and i would like to contribute to your repo. I can write the program in c , c++ or python .

ok , go ahead with C language

**Comment by Kartikey0205** [comment]
@akarshan2602 @0901IT201046 @0901IT201046 please tell me the language in which you feel good, but other than C-Language

**Comment by akarshan2602** [comment]
Python? Or java?

**Comment by Kartikey0205** [comment]
Go ahead with java @akarshan2602

**Comment by 0901IT201046** [comment]
> @akarshan2602 @0901IT201046 @0901IT201046 please tell me the language in which you feel good, but other than C-Language

Sir, I am also in 2nd year and i have good at c and c++ and beginner in python.

**Comment by Kartikey0205** [comment]
> > @akarshan2602 @0901IT201046 @0901IT201046 please tell me the language in which you feel good, but other than C-Language
> 
> Sir, I am also in 2nd year and i have good at c and c++ and beginner in python.


@0901IT201046 go ahead with c++

**Comment by virajshitole** [comment]
I want to work on this issue. can you assign this issue to me.

**Comment by Kartikey0205** [comment]
Go Ahead @virajshitole

**Comment by aamita96** [comment]
Hello @Kartikey0205, I can contribute with JavaScript. Please assign it to me. Thanks.
